"""/Live — feed of Go Live Pulses with shareable permalinks.

Each card shows a pulse with the exact label format the user asked for:

    "Go Live Pulse, generated by <ALGO> at YYYYMMDDHHMMSS"

Below the label sits a copy-pasteable permalink of the form:

    https://<app-host>/Live?pulse=<pulse_id>

When the page is opened with ``?pulse=<id>``, that pulse gets pinned at
the top (easy on mobile when someone shares a link).
"""
from __future__ import annotations

import json
import sys
import time
from datetime import datetime, timezone
from pathlib import Path

_SRC = Path(__file__).resolve().parent.parent / "src"
if str(_SRC) not in sys.path:
    sys.path.insert(0, str(_SRC))

import streamlit as st

try:
    from alpaca_dashboard import live_engine, store
    from alpaca_dashboard.order_executor import is_execution_enabled
    from alpaca_dashboard.pulse_chart import build_pulse_chart
    from alpaca_dashboard.settings import load_algos
except Exception:   # noqa: BLE001
    import traceback
    st.set_page_config(page_title="Live · error", layout="wide", page_icon="🔴")
    st.error("⚠️ /Live page failed to import — traceback:")
    st.code(traceback.format_exc(), language="python")
    st.stop()

st.set_page_config(page_title="Go Live Pulses", layout="wide", page_icon="🔴")
store.init_db()

ALGOS = {a.id: a for a in load_algos()}

# ── Where is this app running? We need that to build shareable permalinks. ──
# Streamlit exposes the browser URL on the client side only. The server-side
# ``st.query_params`` is our proxy — combine with a configurable host name
# via secret (defaults to the production URL).
APP_HOST = st.secrets.get("APP_HOST", "https://alpaca-backtesting.streamlit.app")


def permalink(pulse_id: str) -> str:
    return f"{APP_HOST}/Live?pulse={pulse_id}"


def fmt_gen_at(raw: str | None) -> str:
    """2026-04-15T17:50:58Z → 20260415175058 (per the user's label spec)."""
    if not raw:
        return "unknown"
    try:
        dt = datetime.fromisoformat(raw.replace("Z", "+00:00"))
    except Exception:
        return raw
    return dt.strftime("%Y%m%d%H%M%S")


def fmt_gen_at_human(raw: str | None) -> str:
    """More readable secondary timestamp for the card caption."""
    if not raw:
        return ""
    try:
        dt = datetime.fromisoformat(raw.replace("Z", "+00:00"))
    except Exception:
        return raw
    return dt.astimezone(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")


# ── Header + engine status ──────────────────────────────────────────────────
engine = live_engine.state_snapshot()
st.title("🔴 Go Live Pulses")

header_c1, header_c2, header_c3 = st.columns([3, 2, 2])
with header_c1:
    dot = "🟢" if engine["running"] else "⚪️"
    st.caption(
        f"{dot} Engine: **{'running' if engine['running'] else 'stopped'}** · "
        f"cycle {engine['cycle_sec']}s · "
        f"{len(engine['algos'])} algos × {len(engine['tickers'])} tickers"
    )
with header_c2:
    st.caption(
        f"Last cycle: **{fmt_gen_at_human(engine['last_cycle_at']) or '—'}** · "
        f"+{engine['last_cycle_generated']} new · "
        f"{engine['last_cycle_skipped_dedup']} deduped"
    )
with header_c3:
    st.caption(
        f"Total generated: **{engine['total_generated']}** · "
        f"cycles: {engine['total_cycles']} · "
        f"cache hit rate: {engine['cache'].get('hit_rate', 0)*100:.0f}%"
    )

st.caption(
    "Controls live on the **/Admin** page (Live engine section) or **/Remote_Control**. "
    "This feed is read-only."
)

# ── Sidebar filters ─────────────────────────────────────────────────────────
st.sidebar.header("Filter feed")
max_rows = st.sidebar.slider("Max rows", 10, 500, 50, step=10)
algo_filter = st.sidebar.multiselect(
    "Algos",
    options=list(ALGOS.keys()),
    default=list(ALGOS.keys()),
)
ticker_text = st.sidebar.text_input("Tickers (comma-sep)", "").strip().upper()

# ── Permalink pin ───────────────────────────────────────────────────────────
q = st.query_params
pin_id = (q.get("pulse") or "").strip() if q else ""

# ── Load feed ───────────────────────────────────────────────────────────────
all_rows = store.all_pulses(limit=5000)
live_rows = [
    r for r in all_rows
    if (r.get("job_id") or "").startswith("go_live_")
    and r.get("algo_id") in algo_filter
]
if ticker_text:
    wanted = {t.strip() for t in ticker_text.split(",") if t.strip()}
    live_rows = [r for r in live_rows if r.get("ticker", "").upper() in wanted]

# Newest first
live_rows.sort(key=lambda r: r.get("generated_at") or r.get("created_at") or "", reverse=True)

# Pin the deep-linked pulse at the top if it exists in our feed
if pin_id:
    pinned = [r for r in live_rows if r.get("pulse_id") == pin_id]
    others = [r for r in live_rows if r.get("pulse_id") != pin_id]
    ordered = pinned + others
    if pinned:
        st.success(
            f"📌 Pinned from shared link: `{pin_id}` "
            f"(appears first below; clear by removing `?pulse=…` from URL)"
        )
    else:
        st.info(f"`?pulse={pin_id}` not in the current feed (maybe aged out or filtered).")
        ordered = live_rows
else:
    ordered = live_rows

ordered = ordered[:max_rows]

st.divider()

if not ordered:
    st.info(
        "No Go Live Pulses yet. Start the engine on **/Admin → Live engine**, "
        "or run one cycle now for a quick sanity check."
    )
    st.stop()

st.caption(f"Showing **{len(ordered)}** of {len(live_rows)} live pulses.")

# ── Render cards ────────────────────────────────────────────────────────────
for r in ordered:
    algo_id = r.get("algo_id") or "unknown"
    algo = ALGOS.get(algo_id)
    algo_disp = f"{algo.emoji} {algo.name}" if algo else algo_id
    stamp_compact = fmt_gen_at(r.get("generated_at") or r.get("created_at"))
    stamp_human = fmt_gen_at_human(r.get("generated_at") or r.get("created_at"))
    pulse_id = r.get("pulse_id") or ""
    link = permalink(pulse_id)

    with st.container(border=True):
        # The exact label format the user asked for
        st.markdown(
            f"**Go Live Pulse, generated by {algo_disp} at {stamp_compact}**"
        )
        # Sharable permalink directly below the label
        st.markdown(f"[🔗 Share this pulse]({link})")
        st.code(link, language="text")

        # Order status badge (if execution was triggered for this pulse)
        pulse_orders = store.orders_for_pulse(pulse_id)
        if pulse_orders:
            o = pulse_orders[0]
            badge_color = "green" if o.get("status") == "filled" else "orange"
            st.markdown(
                f"💰 **Order:** {o.get('side')} {o.get('qty')}× {o.get('ticker')} "
                f"— status: **{o.get('status')}** "
                f"{'· fill $' + str(round(float(o['fill_price']), 2)) if o.get('fill_price') else ''}"
            )
        elif is_execution_enabled(algo_id):
            st.caption("⚡ Execution enabled — order pending or PGI too neutral")

        top = st.columns([1, 1, 1, 1, 1])
        top[0].metric("Ticker", r.get("ticker") or "—")
        top[1].metric("PGI", f"{(r.get('pgi') or 0):+.1f}")
        top[2].metric(
            "Action",
            "BUY" if (r.get("pgi") or 0) >= 10 else
            "SELL" if (r.get("pgi") or 0) <= -10 else "WATCH",
        )
        top[3].metric("DTE", f"{r.get('dte') or 0}")
        top[4].metric(
            "Regime", (r.get("market_regime") or "—"),
            help=f"cap: {r.get('cap_bucket') or 'unknown'}",
        )

        st.caption(
            f"📅 {stamp_human} · strategy: **{r.get('strategy_label') or r.get('pulse_type')}** · "
            f"entry ${(r.get('entry_price') or 0):.2f} · "
            f"expires {r.get('expiry') or '—'} · status: **{r.get('status') or '—'}**"
        )

        if r.get("selection_reason"):
            st.caption(f"_{r['selection_reason']}_")

        # ── Interactive chart (same visual as market_pulse web/iOS) ───────
        is_pinned = (pulse_id == pin_id)
        with st.expander(
            "📈 Price chart · P&L · expected move",
            expanded=is_pinned,
        ):
            fig = build_pulse_chart(r)
            if fig:
                st.plotly_chart(fig, use_container_width=False,
                                key=f"chart_{pulse_id}")
            else:
                st.caption(f"Chart unavailable — no price data for {r.get('ticker')}")

            # Strategy detail table (same info as market_pulse pulse card)
            strat_data = {}
            try:
                strat_data = json.loads(r.get("top_rec_json") or "{}")
            except Exception:
                pass

            if strat_data:
                detail_cols = st.columns(4)
                detail_cols[0].metric(
                    "Strategy",
                    strat_data.get("strategy_label") or strat_data.get("strategy_type") or "—",
                )
                strike = strat_data.get("strike")
                if strike:
                    detail_cols[1].metric("Strike", f"${float(strike):.2f}")
                pop = strat_data.get("prob_profit")
                if pop:
                    detail_cols[2].metric("PoP", f"{float(pop):.0f}%")
                rr = None
                mc = strat_data.get("max_profit")
                ml = strat_data.get("max_loss")
                if mc and ml and float(ml) != 0:
                    rr = abs(float(mc) / float(ml))
                if rr:
                    detail_cols[3].metric("R/R", f"{rr:.2f}")

                legs = strat_data.get("legs")
                if legs:
                    st.caption("**Legs:**")
                    for leg in legs:
                        leg_type = leg.get("type", "—")
                        leg_strike = leg.get("strike", "—")
                        leg_delta = leg.get("delta", "")
                        st.caption(
                            f"  {leg_type.upper()} K=${leg_strike} "
                            f"{'Δ=' + str(round(float(leg_delta), 2)) if leg_delta else ''}"
                        )

            # Indicator snapshot
            ind = {}
            try:
                ind = json.loads(r.get("indicators_json") or "{}")
            except Exception:
                pass
            if ind:
                ind_cols = st.columns(6)
                for i, (k, v) in enumerate(ind.items()):
                    if i < 6 and v is not None:
                        ind_cols[i].metric(k.upper(), f"{v}")

            # Raw JSON (collapsed further)
            with st.expander("Raw JSON", expanded=False):
                try:
                    st.json(strat_data)
                except Exception:
                    pass


# ── Auto-refresh while the engine is running so the feed stays live ─────────
if engine["running"]:
    time.sleep(10)
    st.rerun()
